In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("dirty_dataset_50_rows.csv")

In [2]:
df = pd.read_csv("dirty_dataset_50_rows.csv")

In [3]:
#correlation matrix of the dataset, 
# check numeric value relationship between the columns
df.corr(numeric_only=True)

Empty DataFrame
Columns: []
Index: []

In [4]:
df.fillna(df.mean(numeric_only=True))

   EmployeeID     Name      Age     Salary     City Department
0           1      Bob       39   41118.18  Kolkata         HR
1           2    Frank       35   73028.32  Chennai         HR
2           3    Julia       41   34573.28     Pune      Sales
3           4    Julia       50  100536.71  Chennai    Finance
4           5      Ian       51    eightyK  Kolkata         HR
5           6     4673       38   97074.98    Delhi      Sales
6        ID-7    David       27    53965.7     Pune      Sales
7           8    Frank  unknown  114069.37   Jaipur         IT
8           9    Julia       56   86649.22      161      Sales
9          10    David       51        NaN  Chennai         26
10         11      Ian       32   92598.48  Chennai         IT
11         12     9239       50   90441.95  Chennai    Finance
12         13  Charlie       36   36681.84     Pune         HR
13      ID-14    Grace       49   92865.18   Jaipur      Sales
14         15      Ian       28        NaN  Kolkata         IT
15         16      Ian  unknown   69115.83   Mumbai      Sales
16         17      Eva       34   48008.59    Delhi    Finance
17         18     8518       50   69695.01      441         IT
18         19      Bob       23   104500.6  Chennai      Sales
19         20  Charlie       45        NaN     Pune         19
20      ID-21    Grace       38   83704.19    Delhi         IT
21         22    David       58   86203.44   Mumbai         IT
22         23    Alice       50   98343.98     Pune         HR
23         24     8512  unknown   61450.83   Mumbai      Sales
24         25    Helen       51        NaN  Chennai         IT
25         26    Helen       46   47962.41    Delhi      Sales
26         27  Charlie       52   75621.86      330    Finance
27      ID-28      Ian       30   83873.88  Kolkata         IT
28         29    Helen       25   94103.43   Jaipur         HR
29         30     7590       44    missing   Jaipur         32
30         31    Frank       36   43171.41  Kolkata         HR
31         32    Helen      NaN   55311.86   Mumbai         HR
32         33  Charlie       59   88486.25     Pune      Sales
33         34      Eva       45    81113.4     Pune         IT
34      ID-35      Bob       28    missing   Jaipur      Sales
35         36     5728       55  111976.74      449      Sales
36         37      Bob       21   73148.49  Kolkata         IT
37         38    Julia       33   55314.39    Delhi         HR
38         39    Alice       50   67532.69   Mumbai    Finance
39         40      Eva    forty        NaN     Pune         37
40         41      Eva       55    71363.2  Kolkata         IT
41      ID-42     5369       53  103897.63  Chennai         IT
42         43    Frank       48  119526.68    Delhi      Sales
43         44      Eva       51   44786.61    Delhi         IT
44         45      Bob       29    eightyK       61    Finance
45         46    David       34  116758.69    Delhi      Sales
46         47    Grace       58   33959.23   Mumbai      Sales
47         48     1959    forty   99391.83  Kolkata         HR
48      ID-49      Eva       43   40921.97  Kolkata      Sales
49         50    Julia       38        NaN    Delhi         42

In [5]:
df[df['Salary'] == df['Salary'].max()]

   EmployeeID  Name Age   Salary    City Department
29         30  7590  44  missing  Jaipur         32
34      ID-35   Bob  28  missing  Jaipur      Sales

In [6]:

# It will convert the 'Salary' column to numeric, coercing any non-numeric values to NaN. 
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

In [7]:
#Outlier detection using the IQR method
#Outliers are data points that significantly differ from the rest of the dataset. The IQR method identifies outliers by calculating the interquartile range (IQR) and determining which data points fall outside of a specified range.
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Salary'] < lower) | (df['Salary'] > upper)]

print(outliers)

Empty DataFrame
Columns: [EmployeeID, Name, Age, Salary, City, Department]
Index: []

In [8]:
#b
df['Bonus'] = df['Salary'] * 0.10

In [9]:

# iloc 
# It is used for indexing and slicing data in a DataFrame. 
df.iloc[0:5]

  EmployeeID   Name Age     Salary     City Department      Bonus
0          1    Bob  39   41118.18  Kolkata         HR   4111.818
1          2  Frank  35   73028.32  Chennai         HR   7302.832
2          3  Julia  41   34573.28     Pune      Sales   3457.328
3          4  Julia  50  100536.71  Chennai    Finance  10053.671
4          5    Ian  51        NaN  Kolkata         HR        NaN

In [10]:
#loc
#It is a dataframe used for accessing data on a condition
df.loc[df['Salary'] > 50000]

   EmployeeID     Name      Age     Salary     City Department      Bonus
1           2    Frank       35   73028.32  Chennai         HR   7302.832
3           4    Julia       50  100536.71  Chennai    Finance  10053.671
5           6     4673       38   97074.98    Delhi      Sales   9707.498
6        ID-7    David       27   53965.70     Pune      Sales   5396.570
7           8    Frank  unknown  114069.37   Jaipur         IT  11406.937
8           9    Julia       56   86649.22      161      Sales   8664.922
10         11      Ian       32   92598.48  Chennai         IT   9259.848
11         12     9239       50   90441.95  Chennai    Finance   9044.195
13      ID-14    Grace       49   92865.18   Jaipur      Sales   9286.518
15         16      Ian  unknown   69115.83   Mumbai      Sales   6911.583
17         18     8518       50   69695.01      441         IT   6969.501
18         19      Bob       23  104500.60  Chennai      Sales  10450.060
20      ID-21    Grace       38   83704.19    Delhi         IT   8370.419
21         22    David       58   86203.44   Mumbai         IT   8620.344
22         23    Alice       50   98343.98     Pune         HR   9834.398
23         24     8512  unknown   61450.83   Mumbai      Sales   6145.083
26         27  Charlie       52   75621.86      330    Finance   7562.186
27      ID-28      Ian       30   83873.88  Kolkata         IT   8387.388
28         29    Helen       25   94103.43   Jaipur         HR   9410.343
31         32    Helen      NaN   55311.86   Mumbai         HR   5531.186
32         33  Charlie       59   88486.25     Pune      Sales   8848.625
33         34      Eva       45   81113.40     Pune         IT   8111.340
35         36     5728       55  111976.74      449      Sales  11197.674
36         37      Bob       21   73148.49  Kolkata         IT   7314.849
37         38    Julia       33   55314.39    Delhi         HR   5531.439
38         39    Alice       50   67532.69   Mumbai    Finance   6753.269
40         41      Eva       55   71363.20  Kolkata         IT   7136.320
41      ID-42     5369       53  103897.63  Chennai         IT  10389.763
42         43    Frank       48  119526.68    Delhi      Sales  11952.668
45         46    David       34  116758.69    Delhi      Sales  11675.869
47         48     1959    forty   99391.83  Kolkata         HR   9939.183

In [11]:
df['Department'].map({
    'IT':'Tech',
    'HR':'Human Resource'
})

0     Human Resource
1     Human Resource
2                NaN
3                NaN
4     Human Resource
5                NaN
6                NaN
7               Tech
8                NaN
9                NaN
10              Tech
11               NaN
12    Human Resource
13               NaN
14              Tech
15               NaN
16               NaN
17              Tech
18               NaN
19               NaN
20              Tech
21              Tech
22    Human Resource
23               NaN
24              Tech
25               NaN
26               NaN
27              Tech
28    Human Resource
29               NaN
30    Human Resource
31    Human Resource
32               NaN
33              Tech
34               NaN
35               NaN
36              Tech
37    Human Resource
38               NaN
39               NaN
40              Tech
41              Tech
42               NaN
43              Tech
44               NaN
45               NaN
46               NaN
47    Human Resource
48               NaN
49               NaN
Name: Department, dtype: str

In [12]:
#aggregation functions
# It is used to perform operations on a group of data, such as calculating the mean, sum, or count of values in a column.
df['Salary'].agg(['mean', 'max', 'min'])

mean     76071.20825
max     119526.68000
min      33959.23000
Name: Salary, dtype: float64

In [13]:
#cumulative sum
#cumulative sum of the 'Age' column, which calculates the running total of salaries as you move down the rows of the DataFrame.
df['Age'].cumsum()

0                                                    39
1                                                  3935
2                                                393541
3                                              39354150
4                                            3935415051
5                                          393541505138
6                                        39354150513827
7                                 39354150513827unknown
8                               39354150513827unknown56
9                             39354150513827unknown5651
10                          39354150513827unknown565132
11                        39354150513827unknown56513250
12                      39354150513827unknown5651325036
13                    39354150513827unknown565132503649
14                  39354150513827unknown56513250364928
15           39354150513827unknown56513250364928unknown
16         39354150513827unknown56513250364928unknown34
17       39354150513827unknown56513250364928unknown3450
18     39354150513827unknown56513250364928unknown345023
19    39354150513827unknown56513250364928unknown3450...
20    39354150513827unknown56513250364928unknown3450...
21    39354150513827unknown56513250364928unknown3450...
22    39354150513827unknown56513250364928unknown3450...
23    39354150513827unknown56513250364928unknown3450...
24    39354150513827unknown56513250364928unknown3450...
25    39354150513827unknown56513250364928unknown3450...
26    39354150513827unknown56513250364928unknown3450...
27    39354150513827unknown56513250364928unknown3450...
28    39354150513827unknown56513250364928unknown3450...
29    39354150513827unknown56513250364928unknown3450...
30    39354150513827unknown56513250364928unknown3450...
31                                                  NaN
32    39354150513827unknown56513250364928unknown3450...
33    39354150513827unknown56513250364928unknown3450...
34    39354150513827unknown56513250364928unknown3450...
35    39354150513827unknown56513250364928unknown3450...
36    39354150513827unknown56513250364928unknown3450...
37    39354150513827unknown56513250364928unknown3450...
38    39354150513827unknown56513250364928unknown3450...
39    39354150513827unknown56513250364928unknown3450...
40    39354150513827unknown56513250364928unknown3450...
41    39354150513827unknown56513250364928unknown3450...
42    39354150513827unknown56513250364928unknown3450...
43    39354150513827unknown56513250364928unknown3450...
44    39354150513827unknown56513250364928unknown3450...
45    39354150513827unknown56513250364928unknown3450...
46    39354150513827unknown56513250364928unknown3450...
47    39354150513827unknown56513250364928unknown3450...
48    39354150513827unknown56513250364928unknown3450...
49    39354150513827unknown56513250364928unknown3450...
Name: Age, dtype: str

In [14]:
#apply
#It is used to apply a function along an axis of the DataFrame.
df['Salary'].apply(lambda x: x + 5000)

0      46118.18
1      78028.32
2      39573.28
3     105536.71
4           NaN
5     102074.98
6      58965.70
7     119069.37
8      91649.22
9           NaN
10     97598.48
11     95441.95
12     41681.84
13     97865.18
14          NaN
15     74115.83
16     53008.59
17     74695.01
18    109500.60
19          NaN
20     88704.19
21     91203.44
22    103343.98
23     66450.83
24          NaN
25     52962.41
26     80621.86
27     88873.88
28     99103.43
29          NaN
30     48171.41
31     60311.86
32     93486.25
33     86113.40
34          NaN
35    116976.74
36     78148.49
37     60314.39
38     72532.69
39          NaN
40     76363.20
41    108897.63
42    124526.68
43     49786.61
44          NaN
45    121758.69
46     38959.23
47    104391.83
48     45921.97
49          NaN
Name: Salary, dtype: float64

In [15]:
df = df.dropna(subset=['Salary'])

In [16]:
#groupby
#It is used to group the data based on a specific column and perform operations on each group
df.groupby('Department')['Salary'].mean()

Department
Finance    76428.360000
HR         66273.915556
IT         82223.063636
Sales      77319.172667
Name: Salary, dtype: float64

In [17]:
df.to_csv("cleaned_dataset.csv", index=False)